### ISSUE TITLE
For assignment 4, my server never spawns.

### ISSUE THREAD

**Issue by hjhart** [jfahrer/dockerizing_rails#3]
```
MacBook-Pro-5 in ~/workspace/dockerizing_rails ❤️
 |23:36:04| jh |preparation ✗| → docker container run -p 3000:3000 your_docker_id/rails_app:v1 rails s
```
I don't get any output, and when I try to navigate to localhost:3000 I get a `The connection was reset` in firefox.

Let's go through this together!

When I ctrl+c I get a bunch of output that looks like the buffer wasn't flushing.

**Comment by hjhart** [comment]
The same thing happens in assignment 5, when running 
```
 |23:40:17| jh |preparation ✗| → docker container run -p 3000:3000 --link pg \
>   -e POSTGRES_HOST=pg -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=secret \
>   your_docker_id/rails_app:v1 rails s
```

**Comment by hjhart** [comment]
This happens the whole time for me, I'm not totally sure why. Let's discuss.

**Comment by jfahrer** [comment]
Changed the puma config to listen on all interfaces by default. Also added the `-it` flags to make the buffer gets flushed immediately. Thanks
