### ISSUE TITLE
rbenv .ruby-version is noisy if I don't have 2.5.3 installed

### ISSUE THREAD

**Issue by hjhart** [jfahrer/dockerizing_rails#4]
After every command I'm running locally, since I don't have ruby 2.5.3 installed, I'm getting this message:

```
rbenv: version `2.5.3' is not installed
```

Maybe we can just do `echo '2.5.3' > .ruby-version` as part of the `Dockerfile` so it doesn't need to be installed locally.

**Comment by hjhart** [comment]
Actually, it looks like we could just remove that file, since we are running 2.5.5 inside the docker image.

**Comment by jfahrer** [comment]
👍 - I removed the file
